{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-SCNIC
  version: {{ version }}

source:
#  url: https://github.com/shafferm/q2-SCNIC/archive/{{ version }}.tar.gz
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}
    - scnic 0.6.1
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_SCNIC
    - qiime2.plugins.SCNIC

about:
  home: https://github.com/shafferm/q2-SCNIC
  license: BSD
  license_file: LICENSE
  summary: "q2-SCNIC: a qiime2 plugin for SCNIC (https://github.com/shafferm/SCNIC)"
