name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Download QIIME 2 environment file
      run: |
        wget https://raw.githubusercontent.com/qiime2/distributions/refs/heads/dev/2025.4/amplicon/released/qiime2-amplicon-ubuntu-latest-conda.yml -O qiime2-env.yml

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env
        environment-file: qiime2-env.yml
        auto-activate-base: false

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda config --set always_yes yes
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda install -q pytest pytest-cov
        conda install -c conda-forge blas=1.1
        pip install -q flake8 scnic
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip
        make install

    - name: Run linting
      shell: bash -l {0}
      run: |
        make lint
      continue-on-error: true

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Download QIIME 2 environment file
      run: |
        wget https://raw.githubusercontent.com/qiime2/distributions/refs/heads/dev/2025.4/amplicon/released/qiime2-amplicon-ubuntu-latest-conda.yml -O qiime2-env.yml

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env
        environment-file: qiime2-env.yml
        auto-activate-base: false

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda config --set always_yes yes
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda install -q pytest pytest-cov
        conda install -c conda-forge blas=1.1
        pip install -q flake8 scnic
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip
        make install

    - name: Run tests
      shell: bash -l {0}
      run: |
        python -m pytest q2_SCNIC/tests/